### ISSUE TITLE
Printing to Thermal printers with CUPS driver on mac not working

### ISSUE THREAD

**Issue by yubinchen18** [neodynamic/js-escpos-builder#3]
Hi Neodynamic,

First of all your js-escpos-builder is working great on window machines, no problem so far.

But increasingly more of our clients are using Mac, and our custom built script using your library isnt printing anymore to Mac machines.

Is there a way to solve this problem? We found out that the drivers of the printers such as Epson or Star TSP 100 are using CUPS drivers and Mac doesnt support ESC/POS, whats the alternative using this and the JSPManager of your product line up?

**Comment by neodynamic** [comment]
- EPSON printer could be configured accept raw commands by following these steps https://www.neodynamic.com/articles/How-to-configure-RAW-printing-mode-in-macOs-OSX/
- Star printers seem not support raw commands under macOS or Linux per previous customers that were told this fact by Star manufacturer tech support. The solution in this case could be printing PDF or images content instead of ESC/POS commands
